# -*- coding: utf-8 -*-
"""LangChain_WithHuggingFaceAndGoogleGeminiTextGeneration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aZFRLPw7vhw39LTDEeD4in8U7m6qipI
"""

!pip install langchain

!pip install python-dotenv

!pip install huggingface_hub

import langchain

print("Langchain")

from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

import os
# HUGGING_FACE_API=os.getenv("HUGGING_FACE_API")
# print(HUGGING_FACE_API)


from google.colab import userdata
HUGGING_FACE_API = userdata.get('HUGGING_FACE_API')
print(HUGGING_FACE_API)



from google.colab import userdata
GOOGLE_GEMINI_API = userdata.get('GOOGLE_GEMINI_API')
print(GOOGLE_GEMINI_API)



"""**Langchain with Huggig Face**"""

from langchain import HuggingFaceHub

llm1  = HuggingFaceHub(repo_id="mistralai/Mistral-7B-Instruct-v0.2",huggingfacehub_api_token=HUGGING_FACE_API)

response = llm1("What is the capital city of India")
print(response)



"""**Langchain with Google Gemeni**"""

!pip install -U --quiet langchain-google-genai  langchain

from langchain_google_genai import ChatGoogleGenerativeAI
# setup the gemini pro
gemini_llm = ChatGoogleGenerativeAI(model="gemini-pro",google_api_key=GOOGLE_GEMINI_API,temperature=0.3)

result = gemini_llm.invoke("What is the capital city of India?")
print(result.content)