# -*- coding: utf-8 -*-
"""hugging_face_with_langchain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8bl9LdQuf520b8WUQ9ManWP9UJ_qFgK

**Install all required Library**
"""

!pip install huggingface_hub
!pip install transformers
!pip install accelerate
!pip install bitsandbytes
!pip install langchain

"""**Import required library**"""

from langchain import PromptTemplate, HuggingFaceHub, LLMChain

"""**Setting the Environment**"""

from google.colab import userdata
HUGGING_FACE_API = userdata.get('HUGGING_FACE_API')

"""**Text2ext Generation Models | Seq2Seq Models | Encoder-Decoder Models**"""

prompt = PromptTemplate(
    input_variables = ["product"],
    template = "What is good name for a company that makes {product}"
)

"""**google/flan-t5-base**"""

chain = LLMChain(llm = HuggingFaceHub(repo_id= 'google/flan-t5-base',huggingfacehub_api_token=HUGGING_FACE_API,model_kwargs={'temperature':0}),prompt=prompt)

chain.run("Colorful clothes")

"""**facebook/mbart-large-50**"""

chain2 = LLMChain(llm = HuggingFaceHub(repo_id= 'facebook/mbart-large-50',huggingfacehub_api_token=HUGGING_FACE_API,model_kwargs={'temperature':0}),prompt=prompt)

chain2.run("Mobile")