# -*- coding: utf-8 -*-
"""FAIIS_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rf_c89tpzK99LB3gfQgFVyFvOzcbkMeH
"""

!pip -q install langchain
!pip install pypdf
!pip install sentence-transformers==2.2.2

!pip install openai
!pip install tiktoken
!pip install faiss-cpu

!mkdir pdfs

from langchain.document_loaders import PyPDFDirectoryLoader

loader = PyPDFDirectoryLoader("pdfs")
data = loader.load()



data

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(separators="\n",chunk_size=500, chunk_overlap=20)
text_chunks = text_splitter.split_documents(data)

len(text_chunks)

text_chunks[2]

from langchain.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

from langchain.vectorstores import FAISS

vectorstore=FAISS.from_documents(text_chunks, embeddings)

query = "What is correaltion?"

docs = vectorstore.similarity_search(query, k=3)

docs

from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

import os

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

from langchain.llms import OpenAI

llm = OpenAI()

from langchain.chains import RetrievalQA

qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever())

query = "What is correaltion?"

print(qa.run(query))